
services:
  product-service:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 5001:80
    
  elasticsearch:
    container_name: example_es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node

  logstash:
    image: logstash:5.4.3
    volumes:
      - ./logstash:/logstash_dir
    depends_on:
      - elasticsearch
    ports:
      - "5959:5959"

  kibana:
    container_name: kibana
    image: kibana:7.10.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
